In [1]:
#Ваш код
%matplotlib inline

# графики в svg выглядят более четкими
%config InlineBackend.figure_format = 'svg'
import pandas as pd
import numpy as np

import seaborn as sns
# import plotly.express as px
# import plotly.graph_objects as go
import matplotlib.pyplot as plt

# from tqdm import tqdm

import warnings
warnings.filterwarnings('ignore')

# увеличим дефолтный размер графиков
from pylab import rcParams

import statistics

rcParams["figure.figsize"] = 10, 6
sns.set_style("whitegrid", {'axes.grid' : True})

In [ ]:
#Ваш код
datas= pd.read_csv('dataset.csv', sep = ';')
print(datas.head(10))
print('\n')
print('Инфо : ') 
print(datas.info())

In [5]:
#Ваш код
print('Пропуски : ') 
print(datas.isnull().sum())
print('Обработка пропусков..')
datas = datas.dropna(axis=0)
print('Проверка : ')
print(datas.isnull().sum())
print('Дубликаты : ')
print(datas.duplicated().sum())
print('Удаляем... ')
datas = datas.drop_duplicates()
print('Проверка : ')
print(datas.duplicated().sum())
for i in datas:
    print(' Уникальность в признаке : ',i)
    print(datas[i].unique())

# datas['Количество'].unique()
print('\n')
print('Размерность : ',datas.shape)
print('Инфо : ')
print(datas.info())
print('Преобразование полей данных в нужные форматы..')
datas = datas.astype({'Товар': 'int64', 
                       'Количество' : 'int64',
                       'Дата': 'datetime64[ns]',
                       'Клиент': 'string',
                       'Товар': 'string',
                       'Транзакция': 'string'})
print('Инфо : ')
print(datas.info())

Пропуски : 
Дата          0
Транзакция    0
Клиент        0
Товар         0
Количество    0
Сумма         0
dtype: int64
Обработка пропусков..
Проверка : 
Дата          0
Транзакция    0
Клиент        0
Товар         0
Количество    0
Сумма         0
dtype: int64
Дубликаты : 
1127
Удаляем... 
Проверка : 
0
 Уникальность в признаке :  Дата
['03.05.2020 21:43' '20.11.2020 20:46' '08.12.2020 16:28' ...
 '06.07.2021 15:00' '06.07.2021 15:13' '06.07.2021 15:02']
 Уникальность в признаке :  Транзакция
[  954 13796 14431 ... 25398 25399 25412]
 Уникальность в признаке :  Клиент
[    1     2     3 ... 11048 11049 11050]
 Уникальность в признаке :  Товар
[2874. 3586. 4942. ... 3516. 4151. 2334.]
 Уникальность в признаке :  Количество
[1.]
 Уникальность в признаке :  Сумма
[ 8150.    3930.    2860.   ... 17989.98 19989.98 14605.  ]


Размерность :  (47146, 6)
Инфо : 
<class 'pandas.core.frame.DataFrame'>
Int64Index: 47146 entries, 0 to 48302
Data columns (total 6 columns):
 #   Column      Non-N

In [ ]:
df_hits = datas[['Дата','Сумма','Количество','Товар','Транзакция','Клиент']].groupby(['Дата']).sum()
df_hits.resample('M').plot()

In [ ]:
data_sum = datas.groupby(['Товар','Дата'])['Количество','Сумма'].sum()
data_sum

Создадим серии по сумме и по количеству товаров.

In [ ]:
dt = datas[['Дата','Сумма']].groupby(['Дата']).sum().sort_values('Дата')
print('Описательная характеристика серии по сумме: ') 
print('\n')
print(dt.describe())
print('\n')
print(dt.info())

In [ ]:
dtcount = datas[['Дата','Товар']].groupby(['Дата']).count().sort_values('Дата')
print('Описательная характеристика серии по количеству: ') 
print('\n')
print(dtcount.describe())
print('\n')
print(dtcount.info())

Касаемое лучших, худших клиентов


In [14]:
dtclient = datas[['Дата','Клиент','Сумма','Количество']].groupby(['Клиент','Дата'])['Количество','Сумма'].sum().sort_values('Клиент').reset_index()
dtclient.head(10)

Клиент                Дата  Количество    Сумма
0      1 2020-03-05 21:43:00           1   8150.0
1      1 2020-08-12 16:28:00           1   2860.0
2      1 2020-11-20 20:46:00           1   3930.0
3     10 2020-01-05 18:24:00           5  17610.0
4     10 2020-06-15 18:37:00           1   5080.0
5     10 2020-07-06 17:51:00           1   5080.0
6    100 2020-01-05 16:01:00           5  21200.0
7    100 2020-05-09 20:52:00           1   4950.0
8   1000 2020-05-18 18:22:00           1   4645.0
9  10000 2021-05-22 16:08:00           1  20450.0

In [13]:
s = dtclient['Клиент'].value_counts()
s.info()

<class 'pandas.core.series.Series'>
Index: 10989 entries, 3738 to 1438
Series name: Клиент
Non-Null Count  Dtype
--------------  -----
10989 non-null  Int64
dtypes: Int64(1)
memory usage: 182.4 KB


In [ ]:
col_tr = datas['Транзакция'].value_counts()
col_tr

график зависимости от даты

In [ ]:
plt.figure(figsize = (25,6))
plt.subplot(1,2,1)
plt1 = dtcount.Товар.plot()
plt.title('По Количеству')
plt1.set(xlabel = 'Дата', ylabel = 'Количество')

plt.subplot(1,2,2)
plt2 = dt.Сумма.plot()
plt.title('По Сумме')
plt2.set(xlabel = 'Дата', ylabel = 'Сумма')